version: '3'

services:
  compressor:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: img-compressor
    command: /bin/sh /code/entrypoint.sh
    volumes:
      - ./:/code
    ports:
      - 8080:8080
